forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectMultipleField, SubmitField
from wtforms.validators import DataRequired, Email, ValidationError, EqualTo
from .methods import generate_calendar, AuthError


class TimetableForm(FlaskForm):
    cis_username = StringField('CIS Username', validators=[DataRequired()])
    cis_password = PasswordField('CIS Password', validators=[DataRequired()]) 
    modules = SelectMultipleField('Modules', choices=[('mi', 'Michaelmas')], validators=[DataRequired()])
    terms = SelectMultipleField('Terms', choices=[('mi', 'Michaelmas')], validators=[DataRequired()])
    submit = SubmitField('Submit')
    c = None

    def validate_cis_password(self, cis_password):
        login = {'user': cis_username.data, 'pass': cis_password.data}
        try:
            c = generate_calendar(modules, terms, login)
        except AuthError:
            raise ValidationError('Invalid CIS login')

__init__.py
from . import routes, methods

from .routes import bp
from .methods import strip_auth_error

routes.py
from flask import render_template, redirect, send_from_directory, Blueprint, flash, request, session
from werkzeug.security import generate_password_hash
from .forms import TimetableForm
from .methods import generate_calendar, AuthError

bp = Blueprint('timetable', __name__, template_folder='templates')

@bp.route("/")
def index():
    session['timetable'] = True
    form = TimetableForm()
    count = None
    with open('users.txt', 'r+') as f:
        count = len(set(f.readlines()))
    flash('This tool is still in the alpha stage, meaning it has not received enough testing to be sure it runs properly. As such, it might break. Errors in receiving data will be logged, however it is advised you first add the events generated to a separate calendar, check them, and then merge with any existing calendars once you are satisfied with their accuracy.', 'warning')
    return render_template('timetable.html', count=count, title='Timetable Downloader', form=form)

@bp.route('/download', methods={'GET', 'POST'})
def download():
    modules = request.form.getlist('modules')
    terms = request.form.getlist('terms')
    login = {'user': request.form['user'], 'pass': request.form['pass']}
    c = generate_calendar(modules, terms, login)
    #return '<html><body><p>{0}</p></body></html>'.format(c)
    try:
        with open('app/timetable/temp/{0}.ics'.format(login['user']), 'w+') as f:
            f.writelines(c)
        with open('users.txt', 'a+') as f:
            f.write(generate_password_hash(login['user']) + '\n')
        return send_from_directory('timetable/temp', '{0}.ics'.format(login['user']), as_attachment=True)
    except AuthError:
        flash('Incorrect login', 'danger')
        return redirect(url_for('timetable.index'))

@bp.route('/help')
def help():
    count = None
    with open('users.txt', 'r+') as f:
        count = len(set(f.readlines()))
    return render_template('help.html', count=count, title='Timetable Downloader | Help')

@bp.route('/privacy')
def privacy():
    count = None
    with open('users.txt', 'r+') as f:
        count = len(set(f.readlines()))
    return render_template('privacy.html', count=count, title='Timetable Downloader | Privacy')

templates/_formhelper.html
templates/_formhelper.html

templates/help.html
{% extends 'base.html' %}

{% block head %}
<style>
.list-group-item:last-child {
  border-bottom: 1px solid rgba(0,0,0,0.125);
}
</style>
{% endblock %}

{% block nav %}
{% include 'timetable_nav.html' %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-10 offset-1 col-md-5 offset-md-1">
    <div class="text-left">
      <h1 class="mt-5">Using .ics files</h1>
      <p>All good calendar apps allow you to import events from a .ics file. If you have a default calendar app, then simply opening the .ics file will begin the process of importing the events to your calendar. </p>
      <p>For specific instructions, see the list <span class="d-none d-md-inline">to the right</span><span class="d-inline d-md-none">below</span>.</p>
    </div>
  </div>
  <div class="col-10 offset-1 col-md-5 offset-md-0 mt-md-5">
    <div class="text-left">
      <ul class="list-group">
        <a href="https://support.apple.com/en-gb/guide/calendar/icl1023/mac#icl669ab603f" class="list-group-item list-group-item-action">iCalendar</a>
        <a href="https://support.google.com/calendar/thread/3231927?hl=en" class="list-group-item list-group-item-action">Google Calendar</a>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Ben Amies-King</a>
    <a class="nav-link active" href="{{ url_for('timetable.index') }}">Timetable Downloader <span class="text-danger">Alpha</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <a class="nav-link" href="{{ url_for('timetable.help') }}">Help</a>
        <a class="nav-link" href="{{ url_for('timetable.privacy') }}">Privacy</a>
        <span class="mx-auto text-light">Timetables downloaded: {{ count }}</span>
        <a class="ml-auto" href="https://monzo.me/bamiesking/1.00?d=Durham%20Timetable%20Downloader"><button class="btn btn-info">Support me</button></a>
    </div>
</nav>

templates/privacy.html
{% extends 'base.html' %}

{% block nav %}
{% include 'timetable_nav.html' %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-10 offset-1 col-md-5 offset-md-1">
    <div class="text-left">
      <h1 class="mt-5">How your data is used</h1>
      <p>When you submit your CIS username and password, the timetable tool makes a direct query (HTTPS GET) to the CIS timetable website. This is a secure request, and your password is not ever stored on my server.</p>
      <p>The server hosting this site abides by industry security standards. </p>
      <p>CIS usernames are anonymously stored in salted-hashed form in order to track unique users of the tool. This file is not publicly accessible and will never be shared. No other data is recorded, and the .ics files generated are deleted daily.</p>
    </div>
  </div>
</div>
{% endblock %}

templates/timetable.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}

{% block nav %}
{% include 'timetable_nav.html' %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-10 offset-1 col-md-5 offset-md-1">
    <div class="text-left">
      <h1 class="mt-5">Download your Durham Timetable</h1>
      <p class="lead">Select your modules in order to download calendar events for your contact hours.</p>
      <p>Once your timetable information has been retrieved and processed, you will be asked to download a .ics file. Click <a href="{{ url_for('timetable.help') }}">here</a> for more information on how to use this file.</p>
      <p>Passwords are not stored, and usernames are anonymously recorded in order to count unique users. Click <a href="{{ url_for('timetable.privacy') }}">here</a> to read more about privacy.</p>
      <p>Note that the terms option does not mean that only events in that particular term will be included - the university timetable uses that option to include all events which have an occurance in the selected term.</p>
    </div>
  </div>
  <div class="col-10 offset-1 col-md-5 offset-md-0 mt-md-5">
    <form action="{{ url_for('timetable.download') }}" method="POST">
      {% if auth %}
      <div class="alert alert-danger" role="alert">
        Incorrect login
      </div>
      {% endif %}
      <div class="form-group">
        <label for="user">CIS Username</label>
        <input class="form-control" name="user" placeholder="Enter username">
      </div>
      <div class="form-group">
        <label for="pass">CIS Password</label>
        <input type="password" class="form-control" name="pass" placeholder="Enter password">
      </div>
      <div class="form-group">
        <label for="modules">Modules</label>
        <select multiple class="form-control select" id="modules" placeholder="Select modules" name="modules">
          {% include 'modules.html' %}
        </select>
      </div>
      <div class="form-group">
        <label for="terms">Terms</label>
        <select multiple class="form-control" id="terms" placeholder="Select terms" name="terms">
          <option value="mi">Michaelmas</option>
          <option value="ep">Epiphany</option>
          <option value="ea">Easter</option>
        </select>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary text-center mt-3">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/timetable_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Ben Amies-King</a>
    <a class="nav-link active" href="{{ url_for('timetable.index') }}">Timetable Downloader <span class="text-danger">Alpha</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <a class="nav-link" href="{{ url_for('timetable.help') }}">Help</a>
        <a class="nav-link" href="{{ url_for('timetable.privacy') }}">Privacy</a>
        <span class="mx-auto text-light">Timetables downloaded: {{ count }}</span>
        <a class="ml-auto" href="https://monzo.me/bamiesking/1.00?d=Durham%20Timetable%20Downloader"><button class="btn btn-info">Support me</button></a>
    </div>
</nav>